version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anjun_baby_client
    env_file: .env.local
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://anjun_baby_server:8000
    ports:
      - "3000:3000"
    networks:
      - anjun_network
    restart: unless-stopped

networks:
  anjun_network:
    driver: bridge