version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: anjun_baby_server
    ports:
      - "8000:8000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - anjun_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/products"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: anjun_baby_client
    env_file: ./client/.env.local
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://anjun_baby_server:8000
    ports:
      - "3000:3000"
    networks:
      - anjun_network
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy

networks:
  anjun_network:
    driver: bridge
