import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import StoreProvider from "./redux";
import { GoogleWrapper } from "./GoogleWrapper";
import SessionGuard from "./client/(components)/SessionGuard";
import ThemeWelcome from "./client/(components)/ThemeWelcome";
import ErrorBoundary from "./client/(components)/ErrorBoundary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anjun Baby Center",
  description: "Generated by create next app",
};

// Inline script that runs synchronously before React hydration.
// Reads the saved theme from localStorage and immediately applies
// the .theme-boy class to <body> so loading spinners use the right
// theme colour on the very first paint — no pink flash on blue theme.
const themeInitScript = `
  (function() {
    try {
      var t = localStorage.getItem('anjun_theme');
      if (t === 'boy') document.body.classList.add('theme-boy');
    } catch(e) {}
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      {/* Anti-flash: apply saved theme class before any React code runs */}
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>
        <ErrorBoundary>
          <GoogleWrapper>
            <StoreProvider>
              <div className="h-full">
                {/* First-time gender / theme selection overlay */}
                <ThemeWelcome />
                <SessionGuard>
                  {children}
                </SessionGuard>
              </div>
            </StoreProvider>
          </GoogleWrapper>
        </ErrorBoundary>
      </body>
    </html>
  );
}
